Drop code for llvm 15
Still use clang10 for COMPILE_LLVM_RUNTIME. Most changes are related to the opaque ptr change in llvm 15. It requires type when create Load and GEP. It would be nice to generate the type from taichi type.

Known issue.
Still some getPointerElementType use which is Deprecated for llvm 15.
Also some cases use hack to get llvm type for Load/GEP.

Only tested python tests/run_tests.py -v -t3 -a cpu -s on windows.
2 crashes 2 fails.
crashes:
  fp16 crash for my hw not support fp16 for vulkan.
  element_wise crashed in llvm pass, need more time to debug.
fails:
  FAILED tests/python/test_matrix.py::test_matrix_non_constant_index[arch=x64] - RuntimeError: [codegen_llvm.cpp:taichi...
  FAILED tests/python/examples/autodiff/test_minimization.py::test_minimization[none] - assert 0.00016567112470511347 =...