[Misc] Make clang-tidy happy on 'explicit' (#7999)
### Brief Summary

This PR tries to resolve the problem during ` Build and Test / Check
Static Analyzer (pull_request) `. This check takes too much time and
prints out thousands of lines of 'explicit errors' like this:

```
error: single-argument constructors must be marked explicit to avoid unintentional implicit conversions [google-explicit-constructor,-warnings-as-errors]
  one_or_more(Container &&value) : var(std::move(value)) {
  ^
  explicit 
```

This PR also resolves `error: copy constructor should not be declared
explicit` on `GLResourceSet`.

### Walkthrough

<!--
copilot:walkthrough
-->
### <samp>🤖 Generated by Copilot at cbf3891</samp>

* Suppress clang-tidy warning for single-argument constructors of
`one_or_more` class by adding `// NOLINTNEXTLINE` comments
([link](https://github.com/taichi-dev/taichi/pull/7999/files?diff=unified&w=0#diff-6230f8e8c6a8a297f8900dd0f7e212097b07ee7b64fc7fa5a5ffee5af47211a8L14-R34),
). This class is defined in `taichi/common/one_or_more.h` and allows
holding either a single value or a container of values.

---------

Co-authored-by: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>