[lang] Add is_lvalue() to Expr to check writeback_binary operand (#7414)
Issue: #4455

### Brief Summary
Currently, the following error message appears when the user uses the
constant int as the first operand of the `atomic_*()` series of
functions: `AttributeError: 'int' object has no attribute 'ptr'`. To
make matters worse, taichi gives an internal assertion failure when the
user uses some right value expression, e.g., `-x`.

This PR adds a helper function exposed in the Expr python class called
`is_lvalue()`, which the python AST parser can use to check the validity
of operands and throw an error message when a rvalue is used as a write
target.

---------

Co-authored-by: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>