[Lang] Fixed pylint error C0121 (#3135)
* fixed pylint error C0121

* changed presubmit

* changes in tape.py

* Update python/taichi/lang/impl.py

* Auto Format

* fix

Co-authored-by: Ailing <ailzhang@users.noreply.github.com>
Co-authored-by: Taichi Gardener <taichigardener@gmail.com>
Co-authored-by: Ailing Zhang <ailing@taichi.graphics>